export const DELIVERY_DATE_SET = 'DELIVERY_DATE_SET'
export const DELIVERY_MODAL_SHOW = 'DELIVERY_MODAL_SHOW'
export const DELIVERY_MODAL_HIDE = 'DELIVERY_MODAL_HIDE'
export const DELIVERY_MODAL_CART_QUESTION_SHOW = 'DELIVERY_MODAL_CART_QUESTION_SHOW'
export const DELIVERY_MODAL_CART_QUESTION_HIDE = 'DELIVERY_MODAL_CART_QUESTION_HIDE'

export const SELECTED_FILTERS_SET_PRICE_RANGE = 'SELECTED_FILTERS_SET_PRICE_RANGE'
export const SELECTED_FILTERS_UPDATE_SELECTED = 'SELECTED_FILTERS_UPDATE_SELECTED'
export const SELECTED_FILTERS_RESET = 'SELECTED_FILTERS_RESET'
export const SELECTED_FILTERS_RESET_ALL = 'SELECTED_FILTERS_RESET_ALL'

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'

export const FETCH_ADDITIONAL_PRODUCTS_REQUEST = 'FETCH_ADDITIONAL_PRODUCTS_REQUEST'
export const FETCH_ADDITIONAL_PRODUCTS_SUCCESS = 'FETCH_ADDITIONAL_PRODUCTS_SUCCESS'
export const FETCH_ADDITIONAL_PRODUCTS_FAILURE = 'FETCH_ADDITIONAL_PRODUCTS_FAILURE'

export const FETCH_ORDER_CONFIRMATION_REQUEST = 'FETCH_ORDER_CONFIRMATION_REQUEST'
export const FETCH_ORDER_CONFIRMATION_SUCCESS = 'FETCH_ORDER_CONFIRMATION_SUCCESS'
export const FETCH_ORDER_CONFIRMATION_FAILURE = 'FETCH_ORDER_CONFIRMATION_FAILURE'

export const CART_PRODUCT_ADD = 'CART_PRODUCT_ADD'
export const CART_PRODUCT_INCREASE = 'CART_PRODUCT_INCREASE'
export const CART_PRODUCT_DECREASE = 'CART_PRODUCT_DECREASE'
export const CART_PRODUCT_REMOVE = 'CART_PRODUCT_REMOVE'

export const CART_ADDITIONAL_PRODUCT_ADD = 'CART_ADDITIONAL_PRODUCT_ADD'
export const CART_ADDITIONAL_PRODUCT_INCREASE = 'CART_ADDITIONAL_PRODUCT_INCREASE'
export const CART_ADDITIONAL_PRODUCT_DECREASE = 'CART_ADDITIONAL_PRODUCT_DECREASE'
export const CART_ADDITIONAL_PRODUCT_REMOVE = 'CART_ADDITIONAL_PRODUCT_REMOVE'
export const CART_ADDITIONAL_PRODUCTS_CLEAR = 'CART_ADDITIONAL_PRODUCTS_CLEAR'

export const CART_CLEAR = 'CART_CLEAR'

export const CART_PRODUCT_OPTION_DELETE = 'CART_PRODUCT_OPTION_DELETE'

// Naming Convention
// [тип запроса]_[объект]_[действие]