export const SELECTED_FILTERS_SET_PRICE_RANGE = 'SELECTED_FILTERS_SET_PRICE_RANGE'
export const SELECTED_FILTERS_UPDATE_SELECTED = 'SELECTED_FILTERS_UPDATE_SELECTED'
export const SELECTED_FILTERS_RESET = 'SELECTED_FILTERS_RESET'
export const SELECTED_FILTERS_RESET_ALL = 'SELECTED_FILTERS_RESET_ALL'


export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

// Naming Convention
// [тип запроса]_[объект]_[действие]