export const FILTERS = {
  UPDATE_SELECT: 'UPDATE_SELECT',
  SET_SELECTED_PRICE_RANGE: 'SET_SELECTED_PRICE_RANGE',
  RESET_FILTER: 'RESET_FILTER',
  RESET_ALL_FILTERS: 'RESET_ALL_FILTERS'
}

export const CATALOG = {
  PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
  PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
  PRODUCTS_FAILURE: 'PRODUCTS_FAILURE'
}