export const DELIVERY_IS = {
   COURIER: 'COURIER',
   YOURSELF: 'YOURSELF'
}

export const PAY_TYPES = {
   CARD: 'CARD',
   CASH: 'CASH',
   TO_CORPORATE_CARD: 'TO_CORPORATE_CARD',
   ACCOUNT_FOR_A_LEGAL_ENTITY: 'ACCOUNT_FOR_A_LEGAL_ENTITY'
}