export const UPDATE_SELECT = 'UPDATE_SELECT'
export const SET_SELECTED_PRICE_RANGE = 'SET_SELECTED_PRICE_RANGE'
export const RESET_FILTER = 'RESET_FILTER'
export const RESET_ALL_FILTERS = 'RESET_ALL_FILTERS'